/**
 * Sticky footer - sticks to the bottom of the viewport when content is short,
 * pushed down naturally when content overflows (per project UI rules).
 * The parent layout already provides `min-h-screen flex flex-col`, so this
 * element just needs `mt-auto`.
 *
 * NOTE: `new Date().getFullYear()` can differ between server render time and
 * client hydration time (around New Year or across timezones), which triggers
 * a React hydration mismatch. We render the year with `suppressHydrationWarning`
 * on the containing element - React will use the client value after hydration
 * without throwing. This is the Next.js-recommended pattern for date/time
 * content (see https://nextjs.org/docs/messages/react-hydration-error).
 */
import { Github, Heart } from "lucide-react";

export function Footer() {
  return (
    <footer className="mt-auto border-t border-white/10 bg-background/60 backdrop-blur">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <img
              src="/acn-logo.png"
              alt="ACN Logo"
              className="h-5 w-auto object-contain rounded-md"
            />
            <span>
              <span className="font-medium text-foreground">AI Career Navigator</span>

            </span>
          </div>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            <span className="inline-flex items-center gap-1.5">
              Made with <Heart className="h-3.5 w-3.5 text-rose-500" /> for builders
            </span>
            <a
              href="https://github.com"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 hover:text-foreground transition"
            >
              <Github className="h-3.5 w-3.5" />
              Source
            </a>
          </div>
        </div>
        {/* suppressHydrationWarning: the year may differ between server and
            client render (timezone / New Year boundary). React will use the
            client value after hydration without throwing a mismatch error. */}
        <p className="mt-4 text-[11px] text-muted-foreground/70" suppressHydrationWarning>
          © {new Date().getFullYear()} AI Career Navigator. All analyses are generated by AI and should
          be reviewed critically. No resumes are stored - only anonymized skill trends.
        </p>
      </div>
    </footer>
  );
}
